### ISSUE TITLE
The observed voxels are not fully aligned with the ground truth

### ISSUE THREAD

**Issue by Chenyang-Lu** [davidstutz/daml-shape-completion#2]
Hello David,

I notice that in the visualization and h5 file, the observed occupied voxels following the same shape as in the corresponding complete ground truth. 

However, the ground truth and the partially observed input do not fully agree with each other: some voxels are observed as occupied in the input, while these voxels are free space in the ground truth. 

Also see the example in paper.
![20181203094811](https://user-images.githubusercontent.com/28410250/49363398-df589880-f6e1-11e8-87c6-20df3d15224a.png)

But in principle, they should fully agree with each other. Is my understanding correct?

Thanks for replying!

Chenyang

**Comment by shilei-ustcer** [comment]
I think the reason is the depth image's low resolution. @Chenyang-Lu @davidstutz

**Comment by davidstutz** [comment]
Yes. This is mostly an artifact of how the observations have been generated. There are two discreization effects involved. First, the original shape is rendered in depth using low resolution; second, the observations are then voxelized. As both voxelization and depth rendering happens at (relatively) low resolution, the observed voxels are not exactly on (or in) the full shape (in voxelized form). Even in non voxelized form (on the left) the observations are not always perfectly aligned with the shape due to the depth rendering.

**Comment by shilei-ustcer** [comment]
Yes, thank you, David.

**Comment by shilei-ustcer** [comment]
Hi, David

I find that the off_gt mesh you provided in SN-clean low resolution version, in your code if I understand correctly, it should be generated by scale the normalized mesh(during normalizing, a padding 0.25 is forced in your IJCV paper) by 54 as the voxel resolution is 24x54x24, but I find it is actually larger than 54, it's nearly 70. 

If I normalize mesh with a padding 0.25 from off_gt mesh you provided, then when I scale the normalized mesh by 54, and translate it by (27, 12, 12), I find the new generated mesh is covered by your provided off_gt mesh. Is it designed by purpose?

Thank you for replying!

**Comment by davidstutz** [comment]
Can you give an explicit example of which model/file you mean that is larger? I just checked a couple of meshes in SN-clean and also checked the code and could not find any model that is larger than 54.
